[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyFAME"
version = "1.0.0"
authors = [
    { name="Gavin Bosman", email="gavin.bosman12@gmail.com" },
]
description = "PyFAME: the Python Facial Analysis and Manipulation Environment"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.txt" }
keywords = ["Facial Manipulation", "Vision", "Occlusion", "Masking", "Coloring", "Affective Computing"]
dependencies = [
    "opencv-python >= 4.10.0.0",
    "mediapipe >= 0.10.20",
    "pandas >= 2.2.0",
    "numpy <= 2.0.0",
    "scikit-image >= 0.24.0",
    "pydantic >= 2.11.0",
    "matplotlib >= 3.10.0",
    "tqdm >= 4.67.0",
    "av >= 16.1.0"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Typing :: Typed",
]

[project.optional-dependencies]
docs = [
    "mkdocs >= 1.6",
    "mkdocs-material >= 9.5",
    "mkdocstrings[python] >= 0.25",
    "mkdocs-api-autonav >= 0.3",
]
dev = [
    "pyfame[docs]",
    "pytest >= 8.0.0",
    "tox >= 4.24.0",
    "build",
    "twine"
]

[project.urls]
Homepage = "https://github.com/affectivedatascience/PyFAME"

[tool.setuptools.packages.find]
where = ["src"]
include = ["pyfame*"]

[tool.setuptools.package-data]
"pyfame" = ["py.typed", "*typed"]
"pyfame.schema" = ["*.json"]
"pyfame.models.mediapipe" = ["*.task"]
"pyfame.layer.manipulations.overlay.overlay_images" = ["*.png", "*.jpg"]

[tool.pytest.ini_options]
testpaths = ["tests"]