# Compatible color spaces for analyse_facial_colour_means
COLOUR_SPACE_BGR = 47
COLOR_SPACE_BGR = COLOUR_SPACE_BGR
COLOUR_SPACE_HSV = 48
COLOR_SPACE_HSV = COLOUR_SPACE_HSV
COLOUR_SPACE_GREYSCALE = 49
COLOR_SPACE_GRAYSCALE = COLOUR_SPACE_GREYSCALE
COLOR_SPACE_OPTIONS = [COLOUR_SPACE_BGR, COLOR_SPACE_BGR, COLOUR_SPACE_HSV, COLOR_SPACE_HSV, COLOUR_SPACE_GREYSCALE, COLOR_SPACE_GRAYSCALE]
COLOUR_SPACE_OPTIONS = COLOR_SPACE_OPTIONS

# Shift Color options
COLOR_RED = 4
COLOUR_RED = COLOR_RED
COLOR_BLUE = 5
COLOUR_BLUE = COLOR_BLUE
COLOR_GREEN = 6
COLOUR_GREEN = COLOR_GREEN
COLOR_YELLOW = 7
COLOUR_YELLOW = COLOR_YELLOW
SHIFT_COLOR_OPTIONS = [COLOUR_RED, COLOR_RED, COLOUR_BLUE, COLOR_BLUE, COLOUR_GREEN, COLOR_GREEN, COLOUR_YELLOW, COLOR_YELLOW]
SHIFT_COLOUR_OPTIONS = SHIFT_COLOR_OPTIONS

# Fill options for occluded face regions
OCCLUSION_FILL_BLACK = 8
OCCLUSION_FILL_MEAN = 9
OCCLUSION_FILL_OPTIONS = [OCCLUSION_FILL_BLACK, OCCLUSION_FILL_MEAN]

# Blurring methods
BLUR_METHOD_AVERAGE = 11
BLUR_METHOD_GAUSSIAN = 12
BLUR_METHOD_MEDIAN = 13
BLUR_METHOD_OPTIONS = [BLUR_METHOD_AVERAGE, BLUR_METHOD_GAUSSIAN, BLUR_METHOD_MEDIAN]

# Noise methods
NOISE_METHOD_PIXELATE = 18
NOISE_METHOD_SALT_AND_PEPPER = 19
NOISE_METHOD_GAUSSIAN = 20
NOISE_METHOD_OPTIONS = [NOISE_METHOD_PIXELATE, NOISE_METHOD_SALT_AND_PEPPER, NOISE_METHOD_GAUSSIAN]

# Grid shuffling methods
CYCLIC_SHIFT_GRID_SHUFFLE = 27
RANDOM_GRID_SHUFFLE = 28
GRID_SHUFFLE_OPTIONS = [CYCLIC_SHIFT_GRID_SHUFFLE, RANDOM_GRID_SHUFFLE]

# Point Light Display History Modes
SHOW_HISTORY_ORIGIN = 32
SHOW_HISTORY_RELATIVE = 33
POINT_LIGHT_HISTORY_OPTIONS = [SHOW_HISTORY_ORIGIN, SHOW_HISTORY_RELATIVE]

# Frame Shuffle methods
TEMPORAL_SHUFFLE_RANDOM = 34
TEMPORAL_SHUFFLE_RANDOM_WITH_REPLACEMENT = 35
TEMPORAL_SHUFFLE_REVERSE = 36
TEMPORAL_SHUFFLE_RIGHT_CYCLIC_SHIFT = 37
TEMPORAL_SHUFFLE_LEFT_CYCLIC_SHIFT = 38
TEMPORAL_SHUFFLE_PALINDROME = 39
TEMPORAL_SHUFFLE_INTERLEAVE = 40

TEMPORAL_SHUFFLE_METHODS = [TEMPORAL_SHUFFLE_RANDOM, TEMPORAL_SHUFFLE_RANDOM_WITH_REPLACEMENT, TEMPORAL_SHUFFLE_REVERSE, 
                   TEMPORAL_SHUFFLE_RIGHT_CYCLIC_SHIFT, TEMPORAL_SHUFFLE_LEFT_CYCLIC_SHIFT, TEMPORAL_SHUFFLE_PALINDROME,
                   TEMPORAL_SHUFFLE_INTERLEAVE]

# image to video conversion methods
STANDARDISE_IMAGE_SIZES_CROP = 41
STANDARDIZE_IMAGE_SIZES_CROP = STANDARDISE_IMAGE_SIZES_CROP
STANDARDISE_IMAGE_SIZES_PAD = 42
STANDARDIZE_IMAGE_SIZES_PAD = STANDARDISE_IMAGE_SIZES_PAD
STANDARDIZE_IMAGE_SIZES_OPTIONS = [STANDARDISE_IMAGE_SIZES_CROP, STANDARDIZE_IMAGE_SIZES_CROP, STANDARDISE_IMAGE_SIZES_PAD, STANDARDIZE_IMAGE_SIZES_PAD]

# Image Overlay Specifiers
OVERLAY_SUNGLASSES = 43
OVERLAY_GLASSES = 44
OVERLAY_TEARDROP = 45
OVERLAY_FACE_MASK = 46
OVERLAY_PUPILS = 47
OVERLAY_OPTIONS = [OVERLAY_SUNGLASSES, OVERLAY_GLASSES, OVERLAY_TEARDROP, OVERLAY_FACE_MASK, OVERLAY_PUPILS]