from pyfame.utils.constants import *
from pyfame.landmark import *
from pyfame.file_access import *
from pyfame.utils.exceptions import *
import os
import cv2 as cv
import numpy as np
import pandas as pd
from skimage.util import *
import itertools
from datetime import datetime

def generate_shuffled_block_array(file_path:str, shuffle_method:int = TEMPORAL_SHUFFLE_RANDOM, rand_seed:int|None = None, block_duration:int = 1000) -> tuple:
    """ This function takes a given file path and shuffling method, and returns a tuple containing the block_order array and the block size parameter used
    in shuffle_frame_order(). The output of generate_shuffled_block_array can be directly fed into shuffle_frame_order as the block_order parameter.

    Parameters
    ----------
    file_path: str
        A path string to a video file in your current working directory tree.
    shuffle_method: int
        An integer flag indicating the shuffling method used. For a full list of available options please see 
        pyfame_utils.display_shuffle_method_options().
    rand_seed: int | None
        A seed to numpy's random number generator.
    block_duration: int
        The precise time duration in milliseconds of each block of frames.

    Raises
    ------
    OSError: given invalid input file paths.
    TypeError: given invalid parameter types.
    ValueError: given unrecognized values for input parameters.
    """ 

    # Initialize videocapture object
    capture = get_video_capture(file_path=file_path)
    
    # Initialize numpy random number generator
    rng = None
    if rand_seed != None:
        rng = np.random.default_rng(seed=rand_seed)
    else:
        rng = np.random.default_rng()

    # Retrieve relevant capture properties to compute block_size
    num_frames = capture.get(cv.CAP_PROP_FRAME_COUNT)
    fps = capture.get(cv.CAP_PROP_FPS)
    video_duration = (num_frames/fps) * 1000
    num_blocks = (video_duration / block_duration)
    block_size = int(num_frames//num_blocks)

    num_blocks = int(np.ceil(num_blocks))
    block_order = []

    for i in range(num_blocks):
        block_order.append(i)

    match shuffle_method:
        case 34:
            rng.shuffle(block_order)

        case 35:
            block_order = rng.choice(block_order, size=num_blocks, replace=True)
        
        case 36:
            block_order.reverse()

    capture.release()
    return (block_order, block_size)

def apply_temporal_shuffle(file_paths:pd.DataFrame, shuffle_method:int = TEMPORAL_SHUFFLE_RANDOM, rand_seed:int|None = None, 
                           block_duration:int = 1000, drop_last_block:bool = True) -> None:
    """
    For each video file in file_paths, randomly shuffles the frame order by shuffling blocks of frames. 
    Use utility function generate_shuffled_block_array() to pre-generate the block_order list. The output of 
    generate_shuffled_block_array() can be directly passed as the value of input parameter block_order. 

    Alternatively, simply specify the shuffle_method of choice and the block_duration, and shuffle_frame_order() 
    will invoke generate_shuffled_block_array() internally. 
    
    Parameters
    ----------
    file_paths: DataFrame
        A pandas dataframe generated by calling make_paths(). Contains a list of string file paths contained within the 
        root working directory.
    shuffle_method: int
        An integer flag indicating the functions running mode. For a full list of options see `TEMPORAL_SHUFFLE_METHODS`.
    rand_seed: int
        The seed number provided to the numpy random generator instance.
    block_duration: int
        The time duration (in milliseconds) of each block of frames.
    drop_last_block: bool
        A boolean flag indicating if the uneven block of remaining frames should be dropped from the output.

    Raises
    ------
    TypeError: given invalid parameter types.
    FileReadError: given invalid or corrupted file paths.
    UnrecognizedExtensionError: given unknown or invalid video containers.
    """

    # Get the current sys timestamp for a unique output folder
    # name that will identify the processing session
    timestamp = datetime.now().isoformat(timespec='seconds')
    timestamp_str = timestamp.replace(":","-")

    # Extracting the i/o paths from the file_paths dataframe
    if len(file_paths["Absolute Path"]) == 0:
        raise FileReadError(message="File_paths dataframe is empty, please inspect your working folder to ensure you have populated the raw/ directory.")
    
    absolute_paths = file_paths["Absolute Path"]
    relative_paths = file_paths["Relative Path"]

    # Extracting the root directory name from the file paths
    norm_path = os.path.normpath(absolute_paths.iloc[0])
    norm_cwd = os.path.normpath(os.getcwd())
    rel_dir_path, *_ = os.path.split(os.path.relpath(norm_path, norm_cwd))
    parts = rel_dir_path.split(os.sep)
    root_directory = None

    if parts is not None:
        root_directory = parts[0]
    
    if root_directory is None:
        root_directory = "data"
    
    # Test that the directory provided actually exists in the file system before any read/writes
    root_directory_path = os.path.join(norm_cwd, root_directory)

    if not os.path.isdir(root_directory_path):
        raise FileReadError(message=f"Unable to locate the input {root_directory} directory. Please call make_paths() to set up the correct directory structure.")
    if not os.path.isdir(os.path.join(root_directory_path, "raw")):
        raise FileReadError(message=f"Unable to locate the 'raw' subdirectory under root directory '{root_directory}'. Please call make_paths() to set up the correct directory structure.")
    if not os.path.isdir(os.path.join(root_directory_path, "processed")):
        raise FileReadError(message=f"Unable to locate the 'processed' subdirectory under root directory '{root_directory}'. Please call make_paths() to set up the correct directory structure.")
    
    # Pre-made subdirectory structure in the project root
    input_directory = os.path.join(root_directory_path, "raw")
    output_directory = os.path.join(root_directory_path, "processed")
    output_directory = create_output_directory(output_directory, timestamp_str)
    # Map any scaffoled sub-organization from the input dir to the output dir
    map_directory_structure(input_directory, output_directory)

    for i,file in enumerate(absolute_paths):

        if not os.path.isfile(file):
            raise FileReadError(file_path=file)
            
        # Filetype is used to determine the functions running mode
        filename, extension = os.path.splitext(os.path.basename(file))
        codec = "mp4v"
        capture = None
        result = None
        block_size = None

        # Using the file extension to sniff video codec or image container for images
        if extension not in {".mp4", ".mov"}:
            raise UnrecognizedExtensionError()

        # Get the relative file path
        relative_file_path = relative_paths.iloc[i]
        
        subdirectory_names = [
            part for part in relative_file_path.split(os.sep)
            if part not in (root_directory, "raw", os.path.basename(file))
        ]

        # Saving the absolute output path for writing out later
        dir_file_path = os.path.join(output_directory, *subdirectory_names, f"{filename}{extension}")

        capture = get_video_capture(file)
        size = (int(capture.get(3)), int(capture.get(4)))

        result = get_video_writer(dir_file_path, size, video_codec=codec)

        block_order, block_size = generate_shuffled_block_array(file, shuffle_method, rand_seed, block_duration)
        
        match shuffle_method:
            case 34 | 35 | 36:
                shuffled_frames = {}
                counter = 0
                cur_block = []

                # Read in and store all frames
                while ret := capture.read():
                    success, frame = ret
                    if success:
                        cur_block.append(frame)
                        if len(cur_block) == block_size:
                            shuffled_frames.update({counter:cur_block.copy()})
                            cur_block = []
                            counter += 1
                    elif len(cur_block) > 0:
                        shuffled_frames.update({counter:cur_block.copy()})
                        break
                    else:
                        break
                
                if drop_last_block:
                    key = len(shuffled_frames) - 1 
                    shuffled_frames.pop(key)

                    largest_key_idx = block_order.index(max(block_order))
                    del block_order[largest_key_idx]

                original_keys = list(shuffled_frames.keys())
                ref_dict = shuffled_frames.copy()

                for old_key,new_key in zip(original_keys,block_order):
                    new_block = ref_dict[new_key]
                    shuffled_frames.update({old_key:new_block})
                    
                for key in original_keys:
                    block = shuffled_frames.get(key)
                    for out_frame in block:
                        result.write(out_frame)
            
            case 37:
                shuffled_frames = {}
                counter = 0
                cur_block = []

                # Read in and store all frames
                while ret := capture.read():
                    success, frame = ret
                    if success:
                        cur_block.append(frame)
                        if len(cur_block) == block_size:
                            shuffled_frames.update({counter:cur_block.copy()})
                            cur_block = []
                            counter += 1
                    elif len(cur_block) > 0:
                        shuffled_frames.update({counter:cur_block.copy()})
                        break
                    else:
                        break
                
                if drop_last_block:
                    key = len(shuffled_frames) - 1 
                    shuffled_frames.pop(key)
                
                original_keys = list(shuffled_frames.keys())

                # Perform right cyclic shift
                for key in original_keys:
                    block = shuffled_frames.get(key)
                    new_block = [block[-1]] + block[:-1]
                    shuffled_frames.update({key:new_block})
                
                for key in original_keys:
                    block = shuffled_frames.get(key)
                    for out_frame in block:
                        result.write(out_frame)
            
            case 38:
                shuffled_frames = {}
                counter = 0
                cur_block = []

                # Read in and store all frames
                while ret := capture.read():
                    success, frame = ret
                    if success:
                        cur_block.append(frame)
                        if len(cur_block) == block_size:
                            shuffled_frames.update({counter:cur_block.copy()})
                            cur_block = []
                            counter += 1
                    elif len(cur_block) > 0:
                        shuffled_frames.update({counter:cur_block.copy()})
                        break
                    else:
                        break
                
                if drop_last_block:
                    key = len(shuffled_frames) - 1 
                    shuffled_frames.pop(key)
                
                original_keys = list(shuffled_frames.keys())
                # Perform left cyclic shift
                for key in original_keys:
                    block = shuffled_frames.get(key)
                    new_block = block[1:] + [block[0]]
                    shuffled_frames.update({key:new_block})
                    
                for key in original_keys:
                    block = shuffled_frames.get(key)
                    for out_frame in block:
                        result.write(out_frame)
            
            case 39:
                shuffled_frames = {}
                counter = 0
                cur_block = []

                # Read in and store all frames
                while ret := capture.read():
                    success, frame = ret
                    if success:
                        cur_block.append(frame)
                        if len(cur_block) == block_size:
                            shuffled_frames.update({counter:cur_block.copy()})
                            cur_block = []
                            counter += 1
                    elif len(cur_block) > 0:
                        shuffled_frames.update({counter:cur_block.copy()})
                        break
                    else:
                        break
                
                if drop_last_block:
                    key = len(shuffled_frames) - 1 
                    shuffled_frames.pop(key)
                
                shuffled_palindrome_frames = {}
                original_keys = list(shuffled_frames.keys())
                counter = 0

                # Perform palindrome stutter
                for key in original_keys:
                    block = shuffled_frames.get(key)
                    rev_block = block[::-1]
                    shuffled_palindrome_frames.update({counter:block})
                    shuffled_palindrome_frames.update({counter+1:rev_block})
                    counter += 2
                
                palindrome_keys = list(shuffled_palindrome_frames.keys())
                for key in palindrome_keys:
                    block = shuffled_palindrome_frames.get(key)
                    for out_frame in block:
                        result.write(out_frame)

            case 40:
                shuffled_frames = {}
                counter = 0
                cur_block = []

                # Read in and store all frames
                while ret := capture.read():
                    success, frame = ret
                    if success:
                        cur_block.append(frame)
                        if len(cur_block) == block_size:
                            shuffled_frames.update({counter:cur_block.copy()})
                            cur_block = []
                            counter += 1
                    elif len(cur_block) > 0:
                        shuffled_frames.update({counter:cur_block.copy()})
                        break
                    else:
                        break

                shuffled_frames.pop(len(shuffled_frames)-1)

                # perform interleaving of frames
                interleaved_frames = list(itertools.chain(*zip(*(shuffled_frames.values()))))

                for frame in interleaved_frames:
                    result.write(frame)
        
        capture.release()
        result.release()

__all__ = ["apply_temporal_shuffle"]